### ISSUE TITLE
Add Contact info to the Footer

### ISSUE THREAD

**Issue by leandermaben** [acmmanipal/ACM_Website#1]
Replace (Contact info in footer by

Adding links to:
Instagram -  https://www.instagram.com/acm_manipal/?hl=en
facebook - https://www.facebook.com/acm.manipal
github - https://github.com/acmmanipal/
linkedin - https://www.linkedin.com/school/acm-manipal/
medium- https://medium.com/the-acm-manipal-blog

through icons (You can use font-awesome)

**Comment by sig5** [comment]
I would like to take up this issue

**Comment by saaheel** [comment]
I would like to contribute

**Comment by leandermaben** [comment]
@sig5  You can go ahead

**Comment by sig5** [comment]
@leandermaben would you mid re-adding the hacktoberfest-accepted tag to make it elligible for hacktoberfest?

**Comment by sig5** [comment]
I made a pull request for the issue.Please look into it.

**Comment by leandermaben** [comment]
Good Job!
