### ISSUE TITLE
Change favicon.ico for the website.

### ISSUE THREAD

**Issue by ghost** [acmmanipal/ACM_Website#10]
The current favicon used by the website uses the default React favicon. The favicon should be changed to the existing ACM logo.

**Comment by rajatRS** [comment]
Hey @sudo-panda,
I want to contribute in this. So, May I work on this?

**Comment by sudo-panda** [comment]
@rajatRS sure, we will give you the image for the icon soon.

**Comment by rajatRS** [comment]
Thank you @sudo-panda 
But, if you want I could get your logo png from your deployed website which could be converted into a favicon. :)

**Comment by sudo-panda** [comment]
Hey @rajatRS that would be great. 

Since the logo used on the website is rectangular it would need some cropping. Could you please crop the logo to create two versions of favicon.

- The icon having only the acm chapter diamond

- The icon having both the diamonds in the logo along with just the 'm' of manipal.

We will choose whichever one looks better. If you have any doubts feel free to ask.

**Comment by rajatRS** [comment]
Here are some favicon options.
Let me know your views :-



**Favicon Option-1**

![Favicon-1](https://user-images.githubusercontent.com/59203057/95645070-3a772580-0ad9-11eb-9c2b-2a714bfc2f98.png)



**Favicon Option-2**

![Favicon-3](https://user-images.githubusercontent.com/59203057/95645075-48c54180-0ad9-11eb-82f0-f2b14efe554d.png)



**Favicon Option-3**

![Favicon-2](https://user-images.githubusercontent.com/59203057/95645079-524ea980-0ad9-11eb-91e2-2900b9a6c0fe.png)

**Comment by sudo-panda** [comment]
@leandermaben which one do you like out of the ones shown by @rajatRS . Imo the third one looks great.

**Comment by sudo-panda** [comment]
Also @rajatRS if we go with the third one please don't forget fix the cut at the bottom right of m.

**Comment by rajatRS** [comment]
> Also @rajatRS if we go with the third one please don't forget fix the cut at the bottom right of m.

Yeah I will.

**Comment by leandermaben** [comment]
> @leandermaben which one do you like out of the ones shown by @rajatRS . Imo the third one looks great.

Third one looks good.
@rajatRS  You can proceed with it.

**Comment by rajatRS** [comment]
Ok @leandermaben

**Comment by leandermaben** [comment]
Since the favicon you added is white it cannot be seen against the background.
You will need to change the color.

**Comment by leandermaben** [comment]
@sudo-panda What color do you suggest?

**Comment by leandermaben** [comment]
I think blue would be good

**Comment by sudo-panda** [comment]
> I think blue would be good

Yeah or he could add a black background instead of keeping the favicon transparent.

**Comment by leandermaben** [comment]
Black background is also a good idea. I guess it'll look better than blue.
So @sudo-panda  let's finalize white with black background?

**Comment by leandermaben** [comment]
One more thing should the background be rectangular or circular?

**Comment by sudo-panda** [comment]
> So @sudo-panda  let's finalize white with black background?

Yeah sure. @rajatRS please add a black background to the favicon.

**Comment by leandermaben** [comment]
> One more thing should the background be rectangular or circular?

@sudo-panda

**Comment by sudo-panda** [comment]
Anything works imo. You suggest @leandermaben

**Comment by leandermaben** [comment]
Rectangle maybe because the logo is pretty wide and it might require a really big circle to fit.

**Comment by rajatRS** [comment]
Ok @leandermaben  so, I am proceeding with rectangular black background.

**Comment by rajatRS** [comment]
Made another pull request updating the favicon with adding black rectangular background to it. Let me know your views on it.
Also could you please label this issue as "Hacktoberfest" so that it may get counted in Hacktober fest :)

**Comment by leandermaben** [comment]
Good Job!
