### ISSUE TITLE
Add a Navbar

### ISSUE THREAD

**Issue by leandermaben** [acmmanipal/ACM_Website#2]
Add a navbar to the homepage using materialize css.

Add the following options to the right:

- About
- Domains
- Board

**Comment by codewizard26** [comment]
hey can I contribute to make some changes for UI and adding a navbar

**Comment by leandermaben** [comment]
Sure go ahead

**Comment by codewizard26** [comment]
hey, what you assigned me?

**Comment by leandermaben** [comment]
@codewizard26  are you working on this issue?

**Comment by leandermaben** [comment]
Navbar Added
