### ISSUE TITLE
Add icons to the Board Member Cards

### ISSUE THREAD

**Issue by leandermaben** [acmmanipal/ACM_Website#3]
Add linkedin, medium and github icons to the bottom of each board member card in the homepage.

(Use font-awesome icons.)

**Comment by jakubkoje** [comment]
I'm gonna look at it.

**Comment by RheaAdh** [comment]
can i take up this issue?

**Comment by RheaAdh** [comment]
#6 --> this is the reference to the code I've made a pull request for

**Comment by leandermaben** [comment]
Looks Good!

Please replace "class" with "className" in all your i tags

**Comment by RheaAdh** [comment]
i was getting resolve conflict so i closed the prev PR and made a new PR

**Comment by leandermaben** [comment]
Good Job!
