### ISSUE TITLE
Replace class with className

### ISSUE THREAD

**Issue by leandermaben** [acmmanipal/ACM_Website#7]
Replace class with className in all tags in "client/src/components/HomeComponent.js"

**Comment by Gautam-Arora24** [comment]
Can I go ahead and solve this issue @leandermaben ?

**Comment by leandermaben** [comment]
Yeah go ahead

**Comment by Gautam-Arora24** [comment]
Kindly assign it to me @leandermaben

**Comment by Gautam-Arora24** [comment]
Done @leandermaben Kindly let me know

**Comment by leandermaben** [comment]
Good Job!
